<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColaboradorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('colaboradores')->insert([
            [
                'nome_completo' => 'João Silva',
                'apelido' => 'João',
                'nome_pai' => 'Augusto Mello',
                'nome_mae' => 'Márcia Silva',
                'cpf' => '123.456.789-01',
                'data_nascimento' => '1990-01-01',
                'cargo' => 'Desenvolvedor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Maria Souza',
                'apelido' => 'Maria',
                'nome_pai' => 'Sérgio Aguiar',
                'nome_mae' => 'Mariana Souza',
                'cpf' => '987.654.321-01',
                'data_nascimento' => '1985-05-15',
                'cargo' => 'Designer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Carlos Eduardo Lima',
                'apelido' => 'Carlos',
                'nome_pai' => 'Roberto Lima',
                'nome_mae' => 'Fernanda Lima',
                'cpf' => '456.789.123-45',
                'data_nascimento' => '1988-07-22',
                'cargo' => 'Analista de Sistemas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Ana Paula Oliveira',
                'apelido' => 'Ana',
                'nome_pai' => 'José Oliveira',
                'nome_mae' => 'Cristina Oliveira',
                'cpf' => '321.654.987-09',
                'data_nascimento' => '1992-03-10',
                'cargo' => 'Gerente de Projetos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Pedro Henrique Alves',
                'apelido' => 'Pedro',
                'nome_pai' => 'Marcos Alves',
                'nome_mae' => 'Patrícia Alves',
                'cpf' => '654.321.987-12',
                'data_nascimento' => '1995-11-30',
                'cargo' => 'Analista de Marketing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Juliana Costa',
                'apelido' => 'Juliana',
                'nome_pai' => 'Antônio Costa',
                'nome_mae' => 'Lucia Costa',
                'cpf' => '789.123.456-78',
                'data_nascimento' => '1987-09-14',
                'cargo' => 'Recursos Humanos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Lucas Mendes',
                'apelido' => 'Lucas',
                'nome_pai' => 'Ricardo Mendes',
                'nome_mae' => 'Sandra Mendes',
                'cpf' => '987.123.456-32',
                'data_nascimento' => '1993-04-25',
                'cargo' => 'Analista Financeiro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Fernanda Rocha',
                'apelido' => 'Fernanda',
                'nome_pai' => 'Paulo Rocha',
                'nome_mae' => 'Adriana Rocha',
                'cpf' => '123.987.654-09',
                'data_nascimento' => '1991-12-05',
                'cargo' => 'Coordenadora de Vendas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Rafael Gonçalves',
                'apelido' => 'Rafael',
                'nome_pai' => 'Maurício Gonçalves',
                'nome_mae' => 'Isabela Gonçalves',
                'cpf' => '456.321.789-65',
                'data_nascimento' => '1989-06-18',
                'cargo' => 'Engenheiro de Software',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Camila Santos',
                'apelido' => 'Camila',
                'nome_pai' => 'Roberto Santos',
                'nome_mae' => 'Lúcia Santos',
                'cpf' => '654.789.123-45',
                'data_nascimento' => '1994-08-20',
                'cargo' => 'Analista de Qualidade',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Bruno Carvalho',
                'apelido' => 'Bruno',
                'nome_pai' => 'Gustavo Carvalho',
                'nome_mae' => 'Renata Carvalho',
                'cpf' => '321.789.456-12',
                'data_nascimento' => '1996-02-12',
                'cargo' => 'Suporte Técnico',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Amanda Ferreira',
                'apelido' => 'Amanda',
                'nome_pai' => 'Carlos Ferreira',
                'nome_mae' => 'Daniela Ferreira',
                'cpf' => '789.456.123-98',
                'data_nascimento' => '1997-07-07',
                'cargo' => 'Analista de Dados',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Diego Martins',
                'apelido' => 'Diego',
                'nome_pai' => 'Fábio Martins',
                'nome_mae' => 'Carla Martins',
                'cpf' => '456.123.789-32',
                'data_nascimento' => '1998-10-15',
                'cargo' => 'Desenvolvedor Front-end',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Patrícia Nunes',
                'apelido' => 'Patrícia',
                'nome_pai' => 'Marcelo Nunes',
                'nome_mae' => 'Sônia Nunes',
                'cpf' => '123.789.456-78',
                'data_nascimento' => '1999-05-22',
                'cargo' => 'Analista de Marketing Digital',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome_completo' => 'Thiago Ribeiro',
                'apelido' => 'Thiago',
                'nome_pai' => 'Eduardo Ribeiro',
                'nome_mae' => 'Vanessa Ribeiro',
                'cpf' => '987.456.123-09',
                'data_nascimento' => '1990-09-03',
                'cargo' => 'Desenvolvedor Back-end',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}